/* tslint:disable */
/* eslint-disable */
/**
 * Bright Website API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EbookSignUp200ResponseEbook
 */
export interface EbookSignUp200ResponseEbook {
    /**
     * 
     * @type {string}
     * @memberof EbookSignUp200ResponseEbook
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EbookSignUp200ResponseEbook
     */
    url?: string;
}

/**
 * Check if a given object implements the EbookSignUp200ResponseEbook interface.
 */
export function instanceOfEbookSignUp200ResponseEbook(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EbookSignUp200ResponseEbookFromJSON(json: any): EbookSignUp200ResponseEbook {
    return EbookSignUp200ResponseEbookFromJSONTyped(json, false);
}

export function EbookSignUp200ResponseEbookFromJSONTyped(json: any, ignoreDiscriminator: boolean): EbookSignUp200ResponseEbook {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function EbookSignUp200ResponseEbookToJSON(value?: EbookSignUp200ResponseEbook | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'url': value.url,
    };
}

