/* tslint:disable */
/* eslint-disable */
/**
 * Bright Website API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyRecaptchaRequest
 */
export interface VerifyRecaptchaRequest {
    /**
     * Google reCAPTCHA token
     * @type {string}
     * @memberof VerifyRecaptchaRequest
     */
    token: string;
}

/**
 * Check if a given object implements the VerifyRecaptchaRequest interface.
 */
export function instanceOfVerifyRecaptchaRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function VerifyRecaptchaRequestFromJSON(json: any): VerifyRecaptchaRequest {
    return VerifyRecaptchaRequestFromJSONTyped(json, false);
}

export function VerifyRecaptchaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyRecaptchaRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function VerifyRecaptchaRequestToJSON(value?: VerifyRecaptchaRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

