/* tslint:disable */
/* eslint-disable */
/**
 * Bright Website API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyRecaptcha200Response
 */
export interface VerifyRecaptcha200Response {
    /**
     * 
     * @type {string}
     * @memberof VerifyRecaptcha200Response
     */
    score: string;
}

/**
 * Check if a given object implements the VerifyRecaptcha200Response interface.
 */
export function instanceOfVerifyRecaptcha200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "score" in value;

    return isInstance;
}

export function VerifyRecaptcha200ResponseFromJSON(json: any): VerifyRecaptcha200Response {
    return VerifyRecaptcha200ResponseFromJSONTyped(json, false);
}

export function VerifyRecaptcha200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyRecaptcha200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'score': json['score'],
    };
}

export function VerifyRecaptcha200ResponseToJSON(value?: VerifyRecaptcha200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'score': value.score,
    };
}

